export default [
    {
        category : "기본구역",
        os : "WEB",
        name : "메인-지도마커 상세",
        type : "Component",
        page : 1,
        path : "/test"
    },
    {
        category : "로그인",
        os : "WEB",
        name : "스플래시",
        type : "화면",
        page : 8,
        path : "/",
        status : "",
    },
    {
        category : "로그인",
        os : "WEB",
        name : "로그인",
        type : "화면",
        page : 9,
        path : "/login",
        status : "완료",
    },
    {
        category : "로그인",
        os : "WEB",
        name : "비밀번호 재설정 > 휴대폰 인증",
        type : "화면",
        page : 10,
        path : "/searchPassWord",
        status : "완료",
    },
    {
        category : "로그인",
        os : "WEB",
        name : "비밀번호 재설정 > 휴대폰 인증 - 인증코드 입력",
        type : "화면",
        page : 10,
        path : "/searchPassWordCode",
        status : "완료",
    },
    {
        category : "로그인",
        os : "WEB",
        name : "비밀번호 재설정",
        type : "화면",
        page : 11,
        path : "/resetPassWord",
        status : "완료",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 휴대폰인증(입력)",
        type : "화면",
        page : 12,
        path : "/joinPhoneInput",
        status : "완료",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 휴대폰인증(인증)",
        type : "화면",
        page : 12,
        path : "/joinPhoneCheck",
        status : "완료",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 비밀번호등록",
        type : "화면",
        page : 13,
        path : "/enterPassword",
        status : "진행중",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 프로필등록",
        type : "화면",
        page : 13,
        path : "/enterProfile",
        status : "진행중",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 약관동의",
        type : "화면",
        page : 14,
        path : "/provisionAgree",
        status : "완료",

    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 약관동의 - 약관보기",
        type : "화면",
        page : 14,
        path : "/provisionView",
        status : "완료",
    },
    {
        category : "가입하기",
        os : "WEB",
        name : "회원가입 > 권한허용",
        type : "화면",
        page : 15,
        path : "/authorityCheck",
        status : "완료",
    },
    {
        category : "메인",
        os : "AOS",
        name : "메인 > 위치권한허용",
        type : "화면",
        page : 17,
        path : "/accessRight",
        status : "완료",
    },
    {
        category : "메인",
        os : "공통",
        name : "참여그룹 확인",
        type : "화면",
        page : 23,
        path : "/groupCheck",
        status : "완료",
    },
    {
        category : "메인",
        os : "WEB",
        name : "그룹생성",
        type : "화면",
        page : 24,
        path : "/createdGroup",
        status : "완료",
    },
    {
        category : "메인",
        os : "WEB",
        name : "초대코드공유",
        type : "화면",
        page : 26,
        path : "/shareGroup",
        status : "완료",
    },
    {
        category : "메인",
        os : "WEB",
        name : "위치정보 상세 > 위치공유",
        type : "화면",
        page : 29,
        path : "/locationDetail",
        status : "완료",
    },
    {
        category : "메인",
        os : "WEB",
        name : "위치정보 상세 > 위치기록",
        type : "화면",
        page : 31,
        path : "/recordLocation",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "메뉴",
        type : "화면",
        page : 33,
        path : "/groupMain",
        status : "완료",
    },
    {

        category : "메뉴",
        os : "WEB",
        name : "위치공유상태 보기",
        type : "화면",
        page : 35,
        path : "/locationSharingStatus",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "비활동 감지 기능 설정",
        type : "화면",
        page : 36,
        path : "/inactiveSensing",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "그룹설정 > 그룹원관리 (그룹장)",
        type : "화면",
        page : 39,
        path : "/memberSetting",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "안심존 목록",
        type : "화면",
        page : 43,
        path : "/safeZoneList",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "안심존 생성",
        type : "화면",
        page : 44,
        path : "/createSafezone",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "안심존 생성 - 주소검색",
        type : "화면",
        page : 44,
        path : "/searchAddress",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "안심존 보기",
        type : "화면",
        page : 45,
        path : "/safeZoneView",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "안심존 수정",
        type : "화면",
        page : 46,
        path : "/safeZoneEidt",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "근접 알림 수정",
        type : "화면",
        page : 48,
        path : "/proximityAlertEdit",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "SOS 요청, 취소 - 요청",
        type : "화면",
        page : 49,
        path : "/sosView",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "SOS 요청, 취소 - 취소",
        type : "화면",
        page : 49,
        path : "/sosViewCancel",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "내정보 > 사진변경",
        type : "화면",
        page : 51,
        path : "/myProfileEditPhoto",
        status : "완료",
    },
    {
        category : "메뉴",
        os : "WEB",
        name : "FAQ",
        type : "화면",
        page : 57,
        path : "/faqView",
        status : "완료",
    },
    {
        category : "팝업스토어",
        os : "IOS",
        name : "결제",
        type : "화면",
        page : 60,
        path : "/paymentView",
        status : "완료",
    },
    {
        category : "팝업스토어",
        os : "WEB",
        name : "팝업스토어 정보",
        type : "팝업",
        page : 60,
        path : "/popupStoreInfo",
        status : "완료",
    },
    {
        category : "PC",
        os : "WEB",
        name : "PC 기능",
        type : "화면",
        page : 62,
        path : "/pcView",
        status : "완료",
    },
    {
        category : "관리자화면",
        os : "WEB",
        name : "관리자화면",
        type : "화면",
        page : 62,
        path : "/managerPage",
        status : "완료",
    },
]